openapi: 3.0.0
info:
  title: Pizza API
  version: 1.0.0
paths:
  /pizzas:
    get:
      summary: Récupérer toutes les pizzas
      responses:
        '200':
          description: Liste des pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PizzaDto'
    post:
      summary: Créer une nouvelle pizza
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaDto'
      responses:
        '201':
          description: Pizza créée

  /pizza/{id}:
    get:
      summary: Récupérer une pizza par ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la pizza
      responses:
        '200':
          description: Pizza trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaDto'
        '404':
          description: Pizza non trouvée

    put:
      summary: Mettre à jour une pizza existante
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la pizza
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaDto'
      responses:
        '200':
          description: Pizza mise à jour

    delete:
      summary: Supprimer une pizza
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la pizza
      responses:
        '204':
          description: Pizza supprimée

  /pizza/{id}/standard-ingredients:
    get:
      summary: Récupérer les ingrédients standards d'une pizza
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la pizza
      responses:
        '200':
          description: Liste des ingrédients standards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IngredientDto'

  /pizza/{id}/optional-ingredients:
    get:
      summary: Récupérer les ingrédients optionnels d'une pizza
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la pizza
      responses:
        '200':
          description: Liste des ingrédients optionnels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IngredientDto'

  /ingredients:
    get:
      summary: Récupérer tous les ingrédients
      responses:
        '200':
          description: Liste des ingrédients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IngredientDto'
    post:
      summary: Créer un nouvel ingrédient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientDto'
      responses:
        '201':
          description: Ingredient créé

  /ingredients/{id}:
    get:
      summary: Récupérer un ingrédient par ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de l'ingrédient
      responses:
        '200':
          description: Ingredient trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientDto'
        '404':
          description: Ingredient non trouvé

    put:
      summary: Mettre à jour un ingrédient existant
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de l'ingrédient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientDto'
      responses:
        '200':
          description: Ingredient mis à jour

    delete:
      summary: Supprimer un ingrédient
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de l'ingrédient
      responses:
        '204':
          description: Ingredient supprimé

  /orders:
    get:
      summary: Récupérer toutes les commandes
      responses:
        '200':
          description: Liste des commandes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDto'
    post:
      summary: Créer une nouvelle commande
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDto'
      responses:
        '201':
          description: Commande créée

  /orders/{id}:
    get:
      summary: Récupérer une commande par ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la commande
      responses:
        '200':
          description: Commande trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDto'
        '404':
          description: Commande non trouvée

    put:
      summary: Mettre à jour une commande existante
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la commande
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDto'
      responses:
        '200':
          description: Commande mise à jour

    delete:
      summary: Supprimer une commande
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la commande
      responses:
        '204':
          description: Commande supprimée

  /accounts:
    get:
      summary: Récupérer tous les comptes
      responses:
        '200':
          description: Liste des comptes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDto'
    post:
      summary: Créer un nouveau compte
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDto'
      responses:
        '201':
          description: Compte créé

  /accounts/{id}:
    get:
      summary: Récupérer un compte par ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID du compte
      responses:
        '200':
          description: Compte trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
        '404':
          description: Compte non trouvé

    put:
      summary: Mettre à jour un compte existant
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID du compte
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDto'
      responses:
        '200':
          description: Compte mis à jour

    delete:
      summary: Supprimer un compte
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID du compte
      responses:
        '204':
          description: Compte supprimé

components:
  schemas:
    PizzaDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        photo:
          type: string

    IngredientDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        photo:
          type: string
        price:
          type: number
          format: double

    CartDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        idPizza:
          type: integer
          format: int64
        idsIngredients:
          type: array
          items:
            type: integer
            format: int64

    OrderDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        idAccount:
          type: integer
          format: int64

    CommentDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        photo:
          type: string
        idOrder:
          type: integer
          format: int64

    AccountDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        pseudo:
          type: string
        password:
          type: string
        name:
          type: string
        firstname:
          type: string